import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  host: { class: 'flex flex-1 min-h-0' },
  template: `
    <div class="flex flex-1 flex-col items-center justify-center px-6 text-center">
      <h1 class="text-5xl font-bold text-gray-900 mb-4">Welcome to Basset AI</h1>
      <p class="text-xl text-gray-500 max-w-xl mb-10">
        Explore the Agents section to interact with <span class="font-medium text-primary-600">Basset AI</span>-powered conversations and agentic workflows.
      </p>
      <p class="text-base text-gray-400 max-w-lg">
        <span class="font-medium">Disclaimer:</span>
        This application is intended for evaluation and development purposes only.
        Responses are generated by AI models and may be inaccurate or incomplete.
        Do not rely on outputs for financial, legal, medical, or other critical decisions.
      </p>
    </div>
  `
})
export default class HomeComponent {}
