import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { API_BASE_URL, authInterceptor, LOGIN_CONFIG } from 'ngx-common';
import { initializeApp, provideFirebaseApp } from '@angular/fire/app';
import { getAuth, provideAuth } from '@angular/fire/auth';
import {
  ArrowUp,
  Bot,
  Briefcase,
  Calendar,
  ChartBar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Code,
  Copy,
  GraduationCap,
  House,
  Lightbulb,
  LoaderCircle,
  LogIn,
  LogOut,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareX,
  Mic,
  MicOff,
  Monitor,
  Moon,
  Palette,
  PanelLeft,
  Pencil,
  RefreshCw,
  Rocket,
  Scale,
  Settings,
  ShieldAlert,
  SquarePen,
  Sun,
  Trash2,
  TrendingDown,
  TrendingUp,
  User,
  X,
} from 'lucide-angular';
import { LucideAngularModule } from 'lucide-angular';
import { environment } from '../environments/environment';
import { routes } from './app.routes';

const icons = {
  ArrowUp,
  Bot,
  Briefcase,
  Calendar,
  ChartBar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Code,
  Copy,
  GraduationCap,
  House,
  Lightbulb,
  LoaderCircle,
  LogIn,
  LogOut,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  MessageSquareX,
  Mic,
  MicOff,
  Monitor,
  Moon,
  Palette,
  PanelLeft,
  Pencil,
  RefreshCw,
  Rocket,
  Scale,
  Settings,
  ShieldAlert,
  SquarePen,
  Sun,
  Trash2,
  TrendingDown,
  TrendingUp,
  User,
  X,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAuth(() => getAuth()),
    importProvidersFrom(LucideAngularModule.pick(icons)),
    { provide: API_BASE_URL, useValue: environment.apiUrl },
    { provide: LOGIN_CONFIG, useValue: { appName: 'Rustic AI', enableEmail: true, enableGoogle: true, redirectTo: '/agents' } },
  ],
};
